language: swift
osx_image: xcode11

notifications:
  email: false
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
 - brew update
  - gem install bundler
  - bundle
  - cd Example/
  - pod install
script:
  - set -o pipefail
  - xcodebuild -project Example.xcworkspace -scheme Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  